name = "ReviseLoop"
uuid = "3726f4d3-c1dc-421e-9d70-d481f8ce92da"
authors = ["Sean Garborg <se@n-garb.org>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
